### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by Avi-D-coder** [Avi-D-coder/fzf-wordnet.vim#1]
This project is based on https://ddrscott.github.io/blog/2017/fzf-dictionary/

**Comment by Avi-D-coder** [comment]
@ddrscott [fzf-wordnet.vim/bin](https://github.com/Avi-D-coder/fzf-wordnet.vim/tree/master/bin) is your code from the blog post.
I am seeking your permission to continue using it and publishing it under an apache 2 licence.

**Comment by Avi-D-coder** [comment]
@balta2ar  [fzf-wordnet.vim/words/extract-wordnet.sh](https://github.com/Avi-D-coder/fzf-wordnet.vim/blob/master/words/extract-wordnet.sh) is derived from your comments.
I am seeking your permission to continue using it and publishing it under an apache 2 licence.

**Comment by balta2ar** [comment]
> I am seeking your permission to continue using it and publishing it under an apache 2 licence

Permission granted. Happy coding!

**Comment by Avi-D-coder** [comment]
@balta2ar Thanks :)

**Comment by ddrscott** [comment]
You're welcome to reuse and apply a license. I'm glad it's helping someone out. And, wow! That was 2 years ago.

**Comment by Avi-D-coder** [comment]
@ddrscott Thanks. It was a good blog post.

**Comment by ddrscott** [comment]
BTW, @Avi-D-coder are you "_at_ avidcoder" on Twitter?

**Comment by Avi-D-coder** [comment]
@ddrscott no. I should probably make a twitter.
